require 'yelp/fusion'
require 'yelp/fusion/client'
require 'yelp/fusion/configuration'
require 'yelp/fusion/version'
require 'yelp/fusion/error'
require 'yelp/fusion/responses/base'
require 'yelp/fusion/responses/search'
require 'yelp/fusion/responses/models/business'
require 'yelp/fusion/responses/models/categories'
require 'yelp/fusion/responses/models/location'
require 'yelp/fusion/responses/models/region'
require 'yelp/fusion/responses/models/center'
require 'yelp/fusion/endpoint/search'
require 'minitest/autorun'
require 'minitest/pride'require 'vcr'
require 'json'
VCR.configure do |config|
  config.cassette_library_dir = 'Test::vcr_casettes'
  config.hook_into :webmock
end
